-- CreateTable
CREATE TABLE "FormHits" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Form_Id" INTEGER NOT NULL,
    "Timestamp" DATETIME NOT NULL,
    CONSTRAINT "FormHits_Form_Id_fkey" FOREIGN KEY ("Form_Id") REFERENCES "Form" ("Id") ON DELETE RESTRICT ON UPDATE CASCADE
);
