
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "./context/store";
import { Authenticator } from "@/components/Auth/authenticator";
import { Toast } from "@/components/Layout/Toast";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/components/SessionWrapper";
//import { AuthProvider } from "./context/Authstorage";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="" suppressHydrationWarning={false}>
        <Toast />
        <Authenticator>
          <GlobalContextProvider>
            <SessionWrapper>{children}</SessionWrapper>
          </GlobalContextProvider>
        </Authenticator>
      </body>
    </html>
  )
}
